name: Auto Close PRs

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened]

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Author
        run: |
          if [[ "$GITHUB_ACTOR" != "your-username" && "$GITHUB_ACTOR" != "team-member-1" ]]; then
            echo "This repo is not open to external contributions for now"
            gh pr close ${{ github.event.pull_request.number }} -R ${{ github.repository }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
